README.md

Added META SEO inspector to browser extension

Added META SEO inspector

---

README.md

Added Redirect Path to browser extension

Added Redirect Path

---

README.md

Added Nightwatch SEO : Nightwatch is a cloud-based SEO and analytics tool that focuses on rank tracking and reporting. It offers keyword tracking across multiple search engines, competitor analysis, and integration with Google Analytics and Google Search Console.

Add nightwatch.io

---

README.md

"I've made some updates to the readme.md file in this pull request. Specifically, I've added information about two unique and powerful SEO tools, BrightEdge and CognitiveSEO. These additions provide more comprehensive insights into the available SEO tools, helping users make informed choices for their SEO strategies."

Rohan added 2 new seo tools

---

README.md

SERP Counter is a free checker tool that allow you to fastly check  google rank. Using the MST SERP Counter Google Chrome extension, you can examine the live numerical search results to see where you currently stand in the rankings.

Added MST SERP Counter

---

README.md

Visit any competitor's website and get instant data to boost your marketing strategy. Easily access key metrics for any site, including visits over time, site rank by country and category, plus geographic traffic share and traffic sources.

Added Similarweb

---

README.md

See your site through the eyes of a search engine. As it turns out, search engines perceive your site in a way that's vastly different from your perspective. BROWSEO provides you with the kind of x-ray vision that mirrors how search engines view your site.

Added Technical SEO Tool BROWSEO

---

README.md

Hey @hilmanski I have removed most of the links because of conflicts.I will try to make multiple PR's with small changes to contribute now instead on commiting large chuncks so you can easily check the PR's

Removed conflicts

---

README.md

Simulate search engine queries from any location on Google and easily check and track your website or your competitor's rankings. Simulate unbiased search engine queries from any location on Google and easily check your website or your competitor's rankings.

Added Search Simulator extension details

---

README.md

TextOptimizer is a writing assistant tool which helps you write concise, high-quality and targeted content that is rich for your readers and optimized for search engines.

Ability to optimize text extension

---

README.md

Hey @hilmanski  I have added one more tool .I'll keep my PR's short so it doesn't make mess while reviewing.

Updated Readme by adding more tool

---

README.md

Google Lighthouse, a popular free SEO tool, offers detailed reports and actionable tips for enhancing your site's SEO performance. Simply add the Chrome extension and open it while on the desired page for analysis.

Added SEO Browser Extension LightHouse

---

README.md

This PR suggests several improvements to the Awesome SEO tools list:
- Fix several unwanted typos 
- Change descriptions to have uniform capitalization and a period at the end of each description
- Ran auto-lint on the file removing trailing white space and adding other formatting

Fix typos, remove whitespace, fix descriptions for uniform capitalization

---

README.md

Added Keyword Insights https://www.keywordinsights.ai/ to All in one SEO tools section

Added Keyword Insights to All in one SEO tools

---

README.md

SearchSocket is a small tool I built for content optimization. It's free and easy to use. It's powered by a fine-tuned large language model (Llama 3). Thanks for considering it for inclusion.
If you want a quick video rundown, I recently made one here: https://www.youtube.com/watch?v=9lu8An48rF0

Added SearchSocket

---

README.md

Add kwrds.ai as an keyword research tool option

include kwrds.ai as a Keyword Research tool

---

README.md

https://wizardstool.com/ has free functionality - scan up to 2000 URLs for free

Add wizardstool to the list

---

README.md

This PR adds the following tool to the list:
- **BlogBud AI:** Added under the `Content Optimization` category. It is an AI-powered tool for writing SEO-optimized articles.
- Updated the README.md file with the new entry.
- Ensured that this tool was not already listed in the repository.
Let me know if any changes needed. Thank you.

Add BlogBud to the list of SEO tools

---

README.md

Add [TailorTask](https://www.tailortask.ai/) to the list of SEO Content Optimization tools

add TailorTask to the Content Optimization section

---

README.md

Add https://www.checkbot.io/ to SEO Browser Extensions

Add https://www.checkbot.io/ to SEO Browser Extensions

---

README.md

Added [Telescope](https://withtelescope.com/) to the list of "All in one SEO tools".

Add Telescope

---

README.md

- Added That's Rank! (www.thatisrank.com) as a tool to the 'Rank Tracking' category.
- Added KeywordIdeas.xzy (www.keywordideas.xyz) as a tool to the 'Keyword Research' category.

Update README.md with 'Thats Rank' & 'KeywordIdeas'

---

README.md

Add Black and Python SEO Analyzers

Add Black and Python SEO Analyzers

---

README.md

Added a technical SEO tool from Crawling JavaScript: https://github.com/VesterlundCoder/SEO-JavaScript-Crawler-IncRev

Update README.md with technical SEO tool

---

README.md

[SEO Toolbox](https://seotoolbox.site) – A modern all-in-one SEO analysis platform, added under the "All-in-one SEO Tools" section.
[SEO Sidebar](https://chromewebstore.google.com/detail/seo-sidebar/gmmiickdcmghfpliaiefhjafccapgmpp) – A real-time SEO browser extension, added under the "SEO Browser Extensions" section.

Add SEO Toolbox and SEO Sidebar Chrome extension to the awesome-seo-tools list
